2022-11-13 10:30:53,840 [INFO] __main__ - 열두 번째 용의자
2022-11-13 10:30:53,841 [DEBUG] __main__ - 'items'
Traceback (most recent call last):
  File "C:\Users\user\projects\proj\data_manage.py", line 111, in crawl
    data_1_list = json.loads(res_1.text)['items']
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
2022-11-13 15:37:18,692 [INFO] __main__ - 열두 번째 용의자
2022-11-13 15:37:18,692 [DEBUG] __main__ - 'items'
Traceback (most recent call last):
  File "C:\Users\user\projects\proj\data_manage.py", line 113, in crawl
    data_1_list = json.loads(res_1.text)['items']
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
2022-11-13 17:29:46,298 [INFO] __main__ - 파워 오브 도그
2022-11-13 17:29:46,298 [DEBUG] __main__ - 'items'
Traceback (most recent call last):
  File "C:\Users\user\projects\proj\data_manage.py", line 114, in crawl
    data_1_list = json.loads(res_1.text)['items']
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
2022-11-13 19:04:36,996 [INFO] __main__ - 형수님의 하얀 속살 무삭제
2022-11-13 19:04:36,996 [DEBUG] __main__ - 'items'
Traceback (most recent call last):
  File "C:\Users\user\projects\proj\data_manage.py", line 115, in crawl
    data_1_list = json.loads(res_1.text)['items']
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
2022-11-15 20:48:28,573 [INFO] __main__ - 형수님의 하얀 속살 무삭제
2022-11-15 20:48:28,581 [DEBUG] __main__ - 'items'
Traceback (most recent call last):
  File "C:\Users\user\projects\proj\data_manage.py", line 115, in crawl
    data_1_list = json.loads(res_1.text)['items']
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
2022-11-16 10:18:05,934 [INFO] __main__ - 형수님의 하얀 속살 무삭제
2022-11-16 10:18:05,934 [DEBUG] __main__ - 'items'
Traceback (most recent call last):
  File "C:\Users\user\projects\proj\data_manage.py", line 115, in crawl
    data_1_list = json.loads(res_1.text)['items']
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
2022-11-16 10:18:22,962 [INFO] __main__ - 파워 오브 도그
2022-11-16 10:18:22,962 [DEBUG] __main__ - 'items'
Traceback (most recent call last):
  File "C:\Users\user\projects\proj\data_manage.py", line 115, in crawl
    data_1_list = json.loads(res_1.text)['items']
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
